### ISSUE TITLE
Vega layer doesn't show on top of Leaflet in demo

### ISSUE THREAD

**Issue by abudaan** [nyurik/leaflet-vega#1]
But it can be fixed if these lines are commented out:
https://github.com/nyurik/leaflet-vega/blob/master/src/VegaLayer.js#L69-L73

**Comment by Casyfill** [comment]
Same issue, does not work :-(

**Comment by abudaan** [comment]
I made a version that is very much based on this repo; it has a different approach but it might be suitable for your project, see: https://github.com/abudaan/vega-as-leaflet-layer

**Comment by nyurik** [comment]
Sorry everyone, for some reason I totally missed this issue. The demo has been fixed, and everything was updated a bit. @abudaan I just saw your project, very nicely done!  I wonder how we can combine our efforts, as it seems silly to have two :)
