### ISSUE TITLE
Example of icons

### ISSUE THREAD

**Issue by hoopes** [nyurik/leaflet-vega#4]
Hi, I was wondering if this lib supported icons like leaflet, or if that's best left to an actual leaflet geojson layer. Thanks!

**Comment by nyurik** [comment]
@hoopes sorry I missed your question (I should look at all issues more often). The lib is oblivious to any extra functionality of both the leaflet layer (you can add any layers to it directly), or any icons in Vega itself (part of your Vega spec).  The lib simply allows both leaflet & vega work together and stay in sync in terms of what is positioned where. Hope this helps!
